### ISSUE TITLE
[SM] Plugin CallAdmin.smx failed to reload: Could not find required plugin "AFKManager".

### ISSUE THREAD

**Issue by umbr1X** [srcdslab/sm-plugin-CallAdmin#6]
And I have AFK manager 4 installed on my server

**Comment by Rushaway** [comment]
You are missing the include file of AFK Manager in your library when you try to compile the plugin.

**Comment by maximee-leroyy** [comment]
fixed here:
- https://github.com/srcdslab/sm-plugin-CallAdmin/commit/3de9c8e314b7c22caefd138ff49d3e3c8e6eff9e
